/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Dashboard extends javax.swing.JFrame {

    public Dashboard(String taiKhoan, int maQuyen) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Store Inventory");

        if (maQuyen == 1) {
            lblTaiKhoan.setText(taiKhoan);
            lblQuyen.setText("ADMINISTRATOR");
        } else {
            lblTaiKhoan.setText(taiKhoan);
            lblQuyen.setText("EMPLOYEE");
            buttonUsers.setEnabled(false);
            buttonNhaCungCap.setEnabled(false);
            buttonKhachHang.setEnabled(false);
            buttonNhanVien.setEnabled(false);
            buttonSanPham.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navPanel = new javax.swing.JPanel();
        buttonHome = new javax.swing.JButton();
        buttonSanPham = new javax.swing.JButton();
        buttonKhachHang = new javax.swing.JButton();
        buttonNhaCungCap = new javax.swing.JButton();
        buttonHoaDon = new javax.swing.JButton();
        buttonUsers = new javax.swing.JButton();
        buttonNhanVien = new javax.swing.JButton();
        buttonNhapHang = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        buttonDangXuat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTaiKhoan = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        lblQuyen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        navPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/homepage.png"))); // NOI18N
        buttonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });

        buttonSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/productpage.png"))); // NOI18N
        buttonSanPham.setText("Sản phẩm");
        buttonSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSanPhamActionPerformed(evt);
            }
        });

        buttonKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/customerpage.png"))); // NOI18N
        buttonKhachHang.setText("Khách Hàng");
        buttonKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKhachHangActionPerformed(evt);
            }
        });

        buttonNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/supplierpage.png"))); // NOI18N
        buttonNhaCungCap.setText("Nhà phân phối ");
        buttonNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNhaCungCapActionPerformed(evt);
            }
        });

        buttonHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/billpage.png"))); // NOI18N
        buttonHoaDon.setText("Phiếu xuất");
        buttonHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHoaDonActionPerformed(evt);
            }
        });

        buttonUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/userpage.png"))); // NOI18N
        buttonUsers.setText("User");
        buttonUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsersActionPerformed(evt);
            }
        });

        buttonNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/employeepage.png"))); // NOI18N
        buttonNhanVien.setText("Nhân viên");
        buttonNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNhanVienActionPerformed(evt);
            }
        });

        buttonNhapHang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/purchasepage.png"))); // NOI18N
        buttonNhapHang.setText("Phiếu nhập");
        buttonNhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNhapHangActionPerformed(evt);
            }
        });

        menuButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu.png"))); // NOI18N
        menuButton.setText("MENU");
        menuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        displayPanel.setDoubleBuffered(false);
        displayPanel.setFocusable(false);
        displayPanel.setPreferredSize(new java.awt.Dimension(840, 630));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Manage  your  inventory,  transactions  and  personnel,  all  in  one place.<br><br>Click  on  the  Menu  button  to  start.<html>");

        welcomeLabel.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        welcomeLabel.setText("Welcome");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/log-out.png"))); // NOI18N
        buttonDangXuat.setText("Đăng xuất");
        buttonDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtTaiKhoan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/userpage.png"))); // NOI18N
        txtTaiKhoan.setText("User:");

        lblTaiKhoan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTaiKhoan.setText("Tài khoản");

        label1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/key.png"))); // NOI18N
        label1.setText("Quyền:");

        lblQuyen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblQuyen.setText("Quyền");

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonNhaCungCap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonNhapHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addComponent(buttonHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addComponent(txtTaiKhoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTaiKhoan)
                        .addGap(18, 18, 18)
                        .addComponent(label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTaiKhoan)
                        .addComponent(lblTaiKhoan)
                        .addComponent(label1)
                        .addComponent(lblQuyen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addComponent(buttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(buttonNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDangXuatActionPerformed
        int opt = JOptionPane.showConfirmDialog(
                null,
                "<html>Are you sure you want to logout?<br>You will have to login again.<html>",
                "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            dispose();
            LoginPage logPage = new LoginPage();
            logPage.setVisible(true);
        }
    }//GEN-LAST:event_buttonDangXuatActionPerformed

    private void buttonNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNhapHangActionPerformed
        try {
            displayPanel.removeAll();
            PhieuNhapPage purchasePage = new PhieuNhapPage();
            displayPanel.add(purchasePage).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_buttonNhapHangActionPerformed

    private void buttonNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNhanVienActionPerformed
        try {
            displayPanel.removeAll();
            NhanVienPage nhanVienPage = new NhanVienPage();
            displayPanel.add(nhanVienPage).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonNhanVienActionPerformed

    private void buttonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsersActionPerformed
        try {
            displayPanel.removeAll();
            UserPage userPage = new UserPage();
            displayPanel.add(userPage).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonUsersActionPerformed

    private void buttonHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHoaDonActionPerformed
        try {
            displayPanel.removeAll();
            PhieuXuatPage salesPage = new PhieuXuatPage();
            displayPanel.add(salesPage).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonHoaDonActionPerformed

    private void buttonNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNhaCungCapActionPerformed
        displayPanel.removeAll();
        NhaPhanPhoiPage supplierPage = new NhaPhanPhoiPage();
        displayPanel.add(supplierPage).setVisible(true);
    }//GEN-LAST:event_buttonNhaCungCapActionPerformed

    private void buttonKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKhachHangActionPerformed
        try {
            displayPanel.removeAll();
            KhachHangPage customerPage = new KhachHangPage();
            displayPanel.add(customerPage).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonKhachHangActionPerformed

    private void buttonSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSanPhamActionPerformed
        try {
            displayPanel.removeAll();
            SanPhamPage productPage = new SanPhamPage();
            displayPanel.add(productPage).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSanPhamActionPerformed

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        displayPanel.removeAll();
        HomePage homePage1 = new HomePage();
        displayPanel.add(homePage1).setVisible(true);
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed

    }//GEN-LAST:event_menuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDangXuat;
    private javax.swing.JButton buttonHoaDon;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonKhachHang;
    private javax.swing.JButton buttonNhaCungCap;
    private javax.swing.JButton buttonNhanVien;
    private javax.swing.JButton buttonNhapHang;
    private javax.swing.JButton buttonSanPham;
    private javax.swing.JButton buttonUsers;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lblQuyen;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JButton menuButton;
    private javax.swing.JPanel navPanel;
    private javax.swing.JLabel txtTaiKhoan;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
